senky_ajaxbase_statistics:
    path: /ajax_base/statistics
    defaults: { _controller: senky.ajaxbase.controller:handle_statistics }

senky_ajaxbase_who_is_online:
    path: /ajax_base/who_is_online
    defaults: { _controller: senky.ajaxbase.controller:handle_who_is_online }

senky_ajaxbase_pm_note:
    path: /ajax_base/pm_note
    defaults: { _controller: senky.ajaxbase.controller:handle_pm_note }
